services:
  bot:
    image: laporan_bot
    container_name: laporan_web_dan_bot
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - uploads/
            - .git/
            - docker-compose*
            - Dockerfile
        - action: rebuild
          path: package.json
    command: npm run dev
  db:
    ports:
      - "3306:3306"
