services:
  web:
    build: .
    container_name: laporan_web
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
    command: node server.js
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Asia/Makassar

  bot:
    build: .
    container_name: laporan_bot
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
    command: node bot.js
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Asia/Makassar
