services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file: .env
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: laporan_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laporan_harian_kominfo_bot
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Makassar
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p=password" ]
      interval: 5s
      retries: 10

volumes:
  db_data:
