# name: Deployment

# on:
#   push:
#     branches: [main]
#     tags:
#       - 'v*'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Get Git tag (if available)
#         if: startsWith(github.ref, 'refs/tags/')
#         run: echo "DEPLOY_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

#       - name: Set DEPLOY_REF (branch or tag)
#         run: |
#           if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
#             echo "DEPLOY_REF=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
#           else
#             echo "DEPLOY_REF=main" >> $GITHUB_ENV
#           fi

#       - name: Deploy to server
#         run: |
#           ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
#             cd laporan-harian-kominfo-bot
#             git fetch --all --tags
#             git checkout $DEPLOY_REF
#             git pull origin $DEPLOY_REF
#             docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
#             docker image prune -f
#           EOF
